title: Zhipeng Zhou's Homepage
page-top-title: Zhipeng Zhou
top-section-bg-text: Sociology
home-subtitle: Zhipeng Zhou&ensp;|&ensp;周志鹏
copyright-text: '&copy; Zhipeng Zhou 2025-. All Rights Reserved.'
